### ISSUE TITLE
Issue with facebook sdk

### ISSUE THREAD

**Issue by siddateamup** [fidelisa/flutter_plugins#10]
I do not want to use facebook option in my app when I used this library. But is giving facebook SDK error when I include this dependency. how to disable facebook from default options?

**Comment by ypelud** [comment]
Can you give me more informations about this ?
it's on Ios, android, both ?
Can you put a trace ?

**Comment by exallium** [comment]
I have the same issue.  I do not wish to support Facebook Login at this time.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{[...]MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
                                                                                   at com.facebook.internal.Validate.sdkInitialized(Validate.java:143)
                                                                                   at com.facebook.login.LoginManager.<init>(LoginManager.java:79)
                                                                                   at com.facebook.login.LoginManager.getInstance(LoginManager.java:92)
                                                                                   at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin$FacebookSignInDelegate.<init>(FacebookLoginPlugin.java:109)
                                                                                   at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.<init>(FacebookLoginPlugin.java:38)
                                                                                   at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(FacebookLoginPlugin.java:42)
                                                                                   at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:21)
                                                                                   at com.exallium.staticasterflutter.MainActivity.onCreate(MainActivity.kt:11)
                                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by ypelud** [comment]
Ok I understand better ...

If this is a crash issue only, follow the https://pub.dartlang.org/packages/flutter_facebook_login entries without changing the values.

If the problem concerns the size and the sdk embedded, I do not see for the moment how to solve it. Maybe by creating a false module and overloading the dependency. But it's a little weird !!

If some have ideas, I listen to you.

**Comment by joostlek** [comment]
You now have the different ProviderTypes, maybe if you get the _handleFacebook function out of this lib, and put it in another lib, so if you need Facebook login, you just attach that together

**Comment by ypelud** [comment]
The purpose of this plugin is to have all together. I don't want to put some functions into another plugin...
